### ISSUE TITLE
at boot up menu password requested???

### ISSUE THREAD

**Issue by robi62** [corpGibbron/ThinkCentre-M900-hackintosh#1]
hi I just tried to boot with your efi but at boot up menu is asking for a password???
Any ideas why???

**Comment by corpGibbron** [comment]
Oh! Extremely sorry, the password is **_3224_**

**Comment by robi62** [comment]
Thanks One question I boot to Sequoia but its very slow like it has no power… any ideas???

**Comment by corpGibbron** [comment]
First of all,
This EFI is **not yet for macOS 15**.
I am going to make a EFI for it soon till then please boot with Sonoma or contact me on Discord i.e. corpGibbron

**Comment by robi62** [comment]
Ok I will Thanks

**Comment by corpGibbron** [comment]
> Ok I will Thanks

gibbronx is the user
